using System.IdentityModel.Tokens.Jwt;
using System.Net;
using System.Security.Claims;
using App.DAL.EF;
using App.DTO;
using App.DTO.Identity;
using Base.Helpers;
using Domain;
using Domain.Identity;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace WebApp.ApiControllers.Identity;

/// <summary>
/// Account API controller
/// </summary>
[Route("api/v{version:apiVersion}/[controller]/[action]")]
[ApiController]
//[Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
public class AccountController : ControllerBase
{
    
    private readonly IConfiguration _configuration;
    private readonly UserManager<Artist> _userManager;
    private readonly ILogger<AccountController> _logger;
    private readonly SignInManager<Artist> _signInManager;
    private readonly Random _random = new Random();
    private readonly AppDbContext _context;

    /// <summary>
    /// Account controller constructor
    /// </summary>
    /// <param name="configuration"></param>
    /// <param name="userManager"></param>
    /// <param name="logger"></param>
    /// <param name="signInManager"></param>
    /// <param name="context"></param>
    public AccountController(IConfiguration configuration, UserManager<Artist> userManager, ILogger<AccountController> logger, SignInManager<Artist> signInManager, AppDbContext context)
    {
        _configuration = configuration;
        _userManager = userManager;
        _logger = logger;
        _signInManager = signInManager;
        _context = context;
    }

    /// <summary>
    /// Register a new user
    /// </summary>
    /// <param name="registrationData"></param>
    /// <param name="expiresInSeconds"></param>
    /// <returns></returns>
    [HttpPost]
    [Produces("application/json")]
    [Consumes("application/json")]
    [ProducesResponseType<JWTResponse>((int)HttpStatusCode.OK)]
    [ProducesResponseType<RestApiErrorResponse>((int)HttpStatusCode.BadRequest)]
    public async Task<ActionResult<JWTResponse>> Register(
        [FromBody] RegisterInfo registrationData,
        [FromQuery] int expiresInSeconds)
    {
        if (expiresInSeconds <= 0) expiresInSeconds = int.MaxValue;
        expiresInSeconds = expiresInSeconds < _configuration.GetValue<int>("JWTSecurity:ExpiresInSeconds")
            ? expiresInSeconds
            : _configuration.GetValue<int>("JWTSecurity:ExpiresInSeconds");
        
        // is user already registered
        var appUser = await _userManager.FindByEmailAsync(registrationData.Email);
        if (appUser != null)
        {
            _logger.LogWarning("User with email {} is already registered", registrationData.Email);
            return BadRequest(
                new RestApiErrorResponse()
                {
                    Status = HttpStatusCode.BadRequest,
                    Error = $"User with email {registrationData.Email} is already registered"
                }
            );
        }
        
        // register user
        var refreshToken = new AppRefreshToken();
        appUser = new Artist()
        {
            Email = registrationData.Email,
            UserName = registrationData.Email,
            DisplayName = registrationData.DisplayName,
            ProfilePicture = registrationData.ProfilePicture,
            Bio = registrationData.Bio,
            JoinDate = DateTime.UtcNow,
            RefreshTokens = new List<AppRefreshToken>() {refreshToken},
        };
        refreshToken.User = appUser;
        
        var result = await _userManager.CreateAsync(appUser, registrationData.Password);
        if (!result.Succeeded)
        {
            return BadRequest(
                new RestApiErrorResponse()
                {
                    Status = HttpStatusCode.BadRequest,
                    Error = result.Errors.First().Description
                }
            );
        }
        
        result = await _userManager.AddClaimsAsync(appUser, new List<Claim>()
        {
            new(ClaimTypes.GivenName, appUser.DisplayName),
            new(ClaimTypes.Surname, "-")
        });

        if (!result.Succeeded)
        {
            return BadRequest(
                new RestApiErrorResponse()
                {
                    Status = HttpStatusCode.BadRequest,
                    Error = result.Errors.First().Description
                }
            );
        }
        
        // get full user from system with fixed data (maybe there is something generated by identity that we might need
        appUser = await _userManager.FindByEmailAsync(appUser.Email);
        if (appUser == null)
        {
            _logger.LogWarning("User with email {} is not found after registration", registrationData.Email);
            return BadRequest(
                new RestApiErrorResponse()
                {
                    Status = HttpStatusCode.BadRequest,
                    Error = $"User with email {registrationData.Email} is not found after registration"
                }
            );
        }
        
        var claimsPrincipal = await _signInManager.CreateUserPrincipalAsync(appUser);
        var jwt = IdentityExtensions.GenerateJwt(
            claimsPrincipal.Claims,
            _configuration.GetValue<string>("JWTSecurity:Key")!,
            _configuration.GetValue<string>("JWTSecurity:Issuer")!,
            _configuration.GetValue<string>("JWTSecurity:Audience")!,
            expiresInSeconds
        );
        var res = new JWTResponse()
        {
            JWT = jwt,
            RefreshToken = refreshToken.RefreshToken,
        };
        return Ok(res);
        
    }


    /// <summary>
    /// Login user
    /// </summary>
    /// <param name="loginInfo"></param>
    /// <param name="jwtExpiresInSeconds"></param>
    /// <param name="refreshTokenExpiresInSeconds"></param>
    /// <returns></returns>
    [HttpPost]
    public async Task<ActionResult<JWTResponse>> Login(
        [FromBody] 
        LoginInfo loginInfo,
        [FromQuery] 
        int jwtExpiresInSeconds,
        [FromQuery] 
        int refreshTokenExpiresInSeconds
    )
    {
        if (jwtExpiresInSeconds <= 0) jwtExpiresInSeconds = int.MaxValue;
        jwtExpiresInSeconds = jwtExpiresInSeconds < _configuration.GetValue<int>("JWTSecurity:ExpiresInSeconds")
            ? jwtExpiresInSeconds
            : _configuration.GetValue<int>("JWTSecurity:ExpiresInSeconds");
        
        var appUser = await _userManager.FindByEmailAsync(loginInfo.Email);
        if (appUser == null)
        {
            _logger.LogWarning("WebApi login failed, email {} not found", loginInfo.Email);

            await Task.Delay(_random.Next(500, 1000));
            
            return Unauthorized(new RestApiErrorResponse
            {
                Status = HttpStatusCode.Unauthorized,
                Error = "Invalid credentials"
            });
        }
        
        var result = await _signInManager.CheckPasswordSignInAsync(appUser, loginInfo.Password, false);
        if (!result.Succeeded)
        {
            _logger.LogWarning("WebApi login failed, password {} for email {} was wrong", loginInfo.Password,
                loginInfo.Email);
            
            await Task.Delay(_random.Next(500, 1000));
            
            return Unauthorized(new RestApiErrorResponse
            {
                Status = HttpStatusCode.Unauthorized,
                Error = "Invalid credentials"
            });
        }
        
        var claimsPrincipal = await _signInManager.CreateUserPrincipalAsync(appUser);
        
        if (!_context.Database.ProviderName!.Contains("InMemory"))
        {
            var deletedRows = await _context.RefreshTokens
                .Where(t => t.UserId == appUser.Id && t.Expiration < DateTime.UtcNow)
                .ExecuteDeleteAsync();
            _logger.LogInformation("Deleted {} refresh tokens", deletedRows);
        }
        else
        {
            //TODO: inMemory delete for testing
        }        

        var refreshToken = new AppRefreshToken()
        {
            UserId = appUser.Id
        };
        _context.RefreshTokens.Add(refreshToken);
        await _context.SaveChangesAsync();

        var jwt = IdentityExtensions.GenerateJwt(
            claimsPrincipal.Claims,
            _configuration.GetValue<string>("JWTSecurity:Key")!,
            _configuration.GetValue<string>("JWTSecurity:Issuer")!,
            _configuration.GetValue<string>("JWTSecurity:Audience")!,
            jwtExpiresInSeconds
        );

        var responseData = new JWTResponse()
        {
            JWT = jwt,
            RefreshToken = refreshToken.RefreshToken
        };

        return Ok(responseData);
    }


    /// <summary>
    /// Refresh JWT token
    /// </summary>
    /// <param name="tokenRefreshInfo"></param>
    /// <param name="expiresInSeconds"></param>
    /// <returns></returns>
    [HttpPost]
    public async Task<ActionResult<JWTResponse>> TokenRefresh(
        [FromBody] TokenRefreshInfo tokenRefreshInfo,
        [FromQuery] int expiresInSeconds
    )
    {
        if (expiresInSeconds <= 0) expiresInSeconds = int.MaxValue;
        expiresInSeconds = expiresInSeconds < _configuration.GetValue<int>("JWTSecurity:ExpiresInSeconds")
            ? expiresInSeconds
            : _configuration.GetValue<int>("JWTSecurity:ExpiresInSeconds");
        
        // extract jwt object
        JwtSecurityToken? jwt;
        try
        {
            jwt = new JwtSecurityTokenHandler().ReadJwtToken(tokenRefreshInfo.JWT);
            if (jwt == null)
            {
                return BadRequest(
                    new RestApiErrorResponse()
                    {
                        Status = HttpStatusCode.BadRequest,
                        Error = "No token"
                    }
                );
            }
        }
        catch (Exception e)
        {
            return BadRequest(new RestApiErrorResponse()
                {
                    Status = HttpStatusCode.BadRequest,
                    Error = "No token"
                }
            );
        }
        
        
        // validate jwt, ignore expiration date

        if (!IdentityExtensions.ValidateJWT(
                tokenRefreshInfo.JWT,
                _configuration.GetValue<string>("JWTSecurity:Key")!,
                _configuration.GetValue<string>("JWTSecurity:Issuer")!,
                _configuration.GetValue<string>("JWTSecurity:Audience")!
            ))
        {
            return BadRequest("JWT validation fail");
        }

        var userEmail = jwt.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Email)?.Value;
        if (userEmail == null)
        {
            return BadRequest(
                new RestApiErrorResponse()
                {
                    Status = HttpStatusCode.BadRequest,
                    Error = "No email in jwt"
                }
            );
        }

        var appUser = await _userManager.FindByEmailAsync(userEmail);
        if (appUser == null)
        {
            return NotFound("User with email {userEmail} not found");
        }
        
        
        // load and compare refresh tokens
        var refreshToken = await _context.RefreshTokens
            .Where(x => x.UserId == appUser.Id)
            .FirstOrDefaultAsync(x =>
                (x.RefreshToken == tokenRefreshInfo.RefreshToken && x.Expiration > DateTime.UtcNow) ||
                (x.PreviousRefreshToken == tokenRefreshInfo.RefreshToken && x.PreviousExpiration > DateTime.UtcNow)
            );

        if (refreshToken == null)
        {
            return NotFound(
                new RestApiErrorResponse()
                {
                    Status = HttpStatusCode.NotFound,
                    Error = "No valid refresh token found"
                }
            );
        }
        
        // get claims based user
        var claimsPrincipal = await _signInManager.CreateUserPrincipalAsync(appUser);
        
        // generate jwt
        var jwtResponseStr = IdentityExtensions.GenerateJwt(
            claimsPrincipal.Claims,
            _configuration.GetValue<string>("JWTSecurity:Key")!,
            _configuration.GetValue<string>("JWTSecurity:Issuer")!,
            _configuration.GetValue<string>("JWTSecurity:Audience")!,
            expiresInSeconds
        );
        
        refreshToken.PreviousRefreshToken = refreshToken.RefreshToken;
        refreshToken.PreviousExpiration = DateTime.UtcNow.AddMinutes(1);
        refreshToken.RefreshToken = Guid.NewGuid().ToString();
        refreshToken.Expiration = DateTime.UtcNow.AddDays(7);
        
        _context.RefreshTokens.Update(refreshToken);

        await _context.SaveChangesAsync();
        
        _logger.LogInformation("New refresh token: {Token}", refreshToken.RefreshToken);

        return Ok(new JWTResponse
        {
            JWT = jwtResponseStr,
            RefreshToken = refreshToken.RefreshToken
        });
    }
    
    
    /// <summary>
    /// Logout user
    /// </summary>
    /// <param name="logout"></param>
    /// <returns></returns>
    [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
    [HttpPost]
    public async Task<ActionResult> Logout(
        [FromBody]
        LogoutInfo logout)
    {
        // delete the refresh token - so user is kicked out after jwt expiration
        // We do not invalidate the jwt on serverside - that would require pipeline modification and checking against db on every request
        // so client can actually continue to use the jwt until it expires (keep the jwt expiration time short ~1 min)

        var userIdStr = _userManager.GetUserId(User);
        if (userIdStr == null)
        {
            return BadRequest(
                new RestApiErrorResponse()
                {
                    Status = HttpStatusCode.BadRequest,
                    Error = "Invalid refresh token"
                }
            );
        }

        var appUser = await _context.Users
            .Where(u => u.Id == userIdStr).Include(artist => artist.RefreshTokens!)
            .SingleOrDefaultAsync();
        if (appUser == null)
        {
            return NotFound(
                new RestApiErrorResponse()
                {
                    Status = HttpStatusCode.NotFound,
                    Error = "User/Password problem"
                }
            );
        }

        await _context.Entry(appUser)
            .Collection(u => u.RefreshTokens!)
            .Query()
            .Where(x =>
                (x.RefreshToken == logout.RefreshToken) ||
                (x.PreviousRefreshToken == logout.RefreshToken)
            )
            .ToListAsync();

        foreach (var appRefreshToken in appUser.RefreshTokens!)
        {
            _context.RefreshTokens.Remove(appRefreshToken);
        }

        var deleteCount = await _context.SaveChangesAsync();

        return Ok(new {TokenDeleteCount = deleteCount});
    }
    
}